//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class estacionServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estacionServicio()
        {
            this.PuntoCarga = new HashSet<PuntoCarga>();
        }
    
        public int idEstacion { get; set; }
        public int Capacidad { get; set; }
        public string Region { get; set; }
        public string HorarioInicio { get; set; }
        public string HorarioTermino { get; set; }
        public string Direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntoCarga> PuntoCarga { get; set; }
    }
}
